---
# Template configuration files for minishift

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ minishift_templates_copy }}"
  when: minishift_copy_templates
